"""add_conversation_tables

Revision ID: 37659db846e7
Revises: b32d4fc12184
Create Date: 2025-04-01 18:35:11.843418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '37659db846e7'
down_revision = 'b32d4fc12184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先创建枚举类型
    sender_type = sa.Enum('USER', 'AI', 'SYSTEM', name='sendertype')
    sender_type.create(op.get_bind())
    
    # 直接执行SQL，使用USING子句处理类型转换
    op.execute(
        text("ALTER TABLE messages ALTER COLUMN sender_type TYPE sendertype USING sender_type::text::sendertype")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 直接执行SQL，从枚举转回VARCHAR
    op.execute(
        text("ALTER TABLE messages ALTER COLUMN sender_type TYPE VARCHAR USING sender_type::text")
    )
    
    # 删除枚举类型
    sa.Enum(name='sendertype').drop(op.get_bind())
    # ### end Alembic commands ### 