"""add document processing fields

Revision ID: b32d4fc12184
Revises: 60cf5d079c0f
Create Date: 2025-04-01 18:02:00.790089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32d4fc12184'
down_revision = '60cf5d079c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ### 